[project]
name = "ir-faq-mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cloud-sql-python-connector>=1.18.2",
    "pg8000>=1.31.2",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.41",
]
